### ISSUE TITLE
Conflicting Publishing Methods

### ISSUE THREAD

**Issue by tomschenkjr** [socrata/datasync#92]
Running DataSync 1.5.4 and executing an headless HTTP ETL which is running an Upsert defined in the control file while the script executing the DataSync job uses ```--publishMethod replace```. As a result, I'm getting the conflict below.

![image](https://cloud.githubusercontent.com/assets/1639121/6153735/67f0cae4-b1ec-11e4-9b0a-6b3c07fdc045.png)

I thought this conflict was resolved in [1.5.4](https://github.com/socrata/datasync/releases/tag/1.5.4). Is this an expected behavior?

/cc @levyj

**Comment by levyj** [comment]
We have some feedback from Socrata.  It is intentional that DataSync throw an error if the publish methods on the command line and in the control file conflict. (Now that I think of it, that probably also happens if you use the GUI but I did not ask and it does not matter as much.)  That makes a lot of sense in that the "safest" thing to do is to fail if there is ambiguity.  However, it potentially creates some problems for us and possibly others.  Socrata asked that I update this issue with my concerns and suggestions.

The problem for us is that "--publishMethod replace" is hard-coded into our module that accepts parameters and runs a DataSync-HTTP job.  That may have been short-sighted but at the time we created it, I think only replace was supported and --publishMethod was a throw-away.  It was required but ignored in favor of the method in the control file.  If that is right, we may not actually have a problem if --publishMethod can now be omitted entirely since all of our control files should specify a mechanism.

If that is not the case and --publishMethod is still required but now actually used, we do have a problem because we will have conflicts for upsert and append jobs and it would take some re-engineering to change the command line on a per-job basis.  In that case, I can suggest some solutions for Socrata to consider in DataSync:

1) Make --publishMethod optional.

2) Resolve a conflict by favoring the method specified in the control file -- which can be assumed to be customized to the specific dataset or even job (possible to maintain an upsert version and a replace version if one wished).  Returning a notification but not failing the job might make sense.

3) Add a new parameter that amounts to "In case of conflict, do whatever the control file says."  This would be similar to #2 but with no possibility of a conflict being resolved in a way the customer did not instruct.

**Comment by alaurenz** [comment]
This is expected because when the user supplies conflicting publish methods we would rather not make assumptions so it errors out.  The the "--publishMethod" or "-m" flag, however, is not required as long as you supply a control file. The same applies to the '--fileToPublishHasHeaderRow' or '-h' flag. So you can remove those from your calls to DataSync safely as long as you are using DataSync-1.5.4.
